### ISSUE TITLE
[Bug] Icons are downloading and exporting without their 20px bounding box

### ISSUE THREAD

**Issue by HYPD** [Shopify/polaris-icons#293] opened 2019-03-28 19:11 UTC
# Issue summary

Icons downloaded or dragged and dropped from the Polaris Icons UI have their bounding boxes stripped. For example, and icon that should be 20 x 20px appears as 16 x 12px in Sketch. 

The problem with this is that designers expect the bounds of their icons to be correct, removing the extra space means that icons may potentially be used wrongly which could lead to inconsistencies in the product.

## Steps to reproduce

1. Download an icon
1. Open it in sketch
1. Try find the 20px bounding box (it's gone!)

## Expected behavior

When importing to sketch, you should still have a 20x20px bounding box.

With some testing, we found that if you add an additional path in Sketch that is 20 x 20px, and export as an SVG it works. Possible solutions (I dont know the feasibility of these):

- I wonder if we could somehow apply this to each SVG on download/in the UI
- Apply the path to each svg and strip out the path when being referenced 

## Additional context
@kaelig mentioned we might try to add 
`<rect width="20" height="20" fill="none" id="BoundingBox"/>`
into each SVG.

**Comment by kaelig** [comment] 2019-09-04 04:57
Closing as this is not a bug, but a behaviour in Sketch that we won't spend resources finding a workaround for.

**Closed by kaelig** 2019-09-04 04:57 UTC
Labels: Bug
